# Copy this file as settings.yml
gitlabApiUrl: "https://your.gitlab.url/api/v4/"
gitlabToken: "token-here" # Replace this!
gitlabGroupId: 2
gitlabIncludeProjects: "1:Project 1,2:Project 2"
gitlabExcludeProjects: ""
gitlabTypeLabel: "Type::"
#gitlabExcludeTypeLabels: "Bug,Vulnerability"
gitlabPriorityLabel: "Priority::"
#gitlabExcludePriorityLabels: "Highest,Lowest"
#gitlabPriorityOrder: "Low,Normal,High"
gliziRaisedByLabels: "Title{~UAT}:Raised by UAT,Organisation{!=Not Your Organisation}:Raised by Customer,Organization{Your Organization}:Roadmap Item,*:Other (Default)"
