name: Build & Release

# Only build release from master
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - '.vscode'
    - '.idea'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Find Version & Build
        id: build
        run: |
          PACKAGE_JSON_VERSION=$(cat package.json | grep version | tr '"' ' ' | awk '{print $3}')
          echo "${PACKAGE_JSON_VERSION}"
          echo "release_version=${PACKAGE_JSON_VERSION}" >> $GITHUB_ENV
          gem install rake
          gem install zendesk_apps_tools
          ./build.sh
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_JSON_VERSION }}
          name: ${{ env.PACKAGE_JSON_VERSION }} (${{ github.sha }})
          body: Release notes needed...
          draft: true # All releases default to being a draft
          prerelease: false
          files: dist/glizi.zip